### ISSUE TITLE
Exercise 4.2 Github Task

### ISSUE THREAD

**Issue by casc-nellv** [casc-nellv/skills-introduction-to-github#3]
### Tasks for Github Exercise 4.1.pptx:

- [ ] Created a Terraform template for Azure VM deployment.
- [ ] Deployed the template to Azure using a virtual environment.
- [ ] Created a new branch and pushed changes.
- [ ] Created a pull request and added "casc-christianm" as a reviewer.
